[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
llrt = "6Wxo7wa72xkz5CKA9UWPTzn8Nmz6j55SfFjSYn8fewoV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
